### PR TITLE
add sth

### PR DESCRIPTION
**Pull request by icy4ever**
### 修复的问题：
- 拼写错误

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/bk-cmdb?pullRequest=6398) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/bk-cmdb?pullRequest=6398) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/bk-cmdb?pullRequest=6398) it.</sub>

**Comment by wjyfelen** [comment]
感谢发现问题，需要增加个gpg签名，然后才能merge哈

**Comment by icy4ever** [comment]
这样就可以了是吧

**Review by wcy00000000000000 — APPROVED** [review]

**Review by wjyfelen — APPROVED** [review]

**Comment by ZQHcode** [comment]
你好，这个PR可以麻烦提到3.10分支吗，然后我们这边合入

**Comment by wjyfelen** [comment]
你好，感谢您对cmdb的支持，需要麻烦您做以下几步:
1、录入一个issue
2、签署CLA协议
3、下载最新的3.10.x代码 在3.10.x代码进行修改
4、如果有冲突处需要您处理完冲突
本pr我先关掉了。请您再按照以上几步再提交新的pr，我们会第一时间进行处理。如果还有其他疑问，可以直接邮件联系我wjyfelen@163.com

**Pull request closed without merging**
